apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer   # ← this must be present!
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


