apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-service  # must match your fastapi deployment label
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000




